apiVersion: v1
kind: Service
metadata:
  name: quixy-harbor-portal-nodeport
  namespace: harbor
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32002
  selector:
    app.kubernetes.io/component: portal
